[build]
  command = "cd executive-care-services && npm install && npm run build"
  publish = "executive-care-services/.next"

[build.environment]
  NODE_VERSION = "20.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the wildcard redirect to index.html as it may interfere with Next.js routing
# This is handled by Next.js when using @netlify/plugin-nextjs

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/public/*"  # Ensure this matches your directory structure
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
